"""initial schema

Revision ID: ad53479ba506
Revises:
Create Date: 2026-08-01 12:17:28.488043
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ad53479ba506"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_call_ledger",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("playlist_id", sa.String(length=128), nullable=True),
        sa.Column("publication_id", sa.String(length=36), nullable=True),
        sa.Column("is_mutation", sa.Boolean(), nullable=False),
        sa.Column("counts_against_automatic_budget", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("status_class", sa.String(length=16), nullable=True),
        sa.Column("retry_after_seconds", sa.Integer(), nullable=True),
        sa.Column("circuit_state", sa.String(length=16), nullable=True),
        sa.Column("response_size_bytes", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_call_ledger", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ledger_operation_started", ["operation", "started_at"], unique=False
        )
        batch_op.create_index("ix_ledger_started", ["started_at"], unique=False)

    op.create_table(
        "artist_affinity",
        sa.Column("artist_id", sa.String(length=128), nullable=False),
        sa.Column("plays_1d", sa.Integer(), nullable=False),
        sa.Column("plays_7d", sa.Integer(), nullable=False),
        sa.Column("plays_30d", sa.Integer(), nullable=False),
        sa.Column("plays_all", sa.Integer(), nullable=False),
        sa.Column("decayed_reward", sa.Float(), nullable=False),
        sa.Column("last_played_at", sa.DateTime(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("artist_id"),
    )
    op.create_table(
        "artists",
        sa.Column("artist_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("artist_id"),
    )
    op.create_table(
        "candidate_edges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("seed_video_id", sa.String(length=64), nullable=False),
        sa.Column("candidate_video_id", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_key", sa.String(length=128), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "seed_video_id",
            "candidate_video_id",
            "source_type",
            "source_key",
            name="uq_candidate_edge",
        ),
    )
    with op.batch_alter_table("candidate_edges", schema=None) as batch_op:
        batch_op.create_index("ix_candidate_expires", ["expires_at"], unique=False)

    op.create_table(
        "feature_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("generation_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("feature_schema_version", sa.String(length=24), nullable=False),
        sa.Column("features_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generation_id", "video_id", name="uq_feature_generation_video"),
    )
    with op.batch_alter_table("feature_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_feature_created", ["created_at"], unique=False)
        batch_op.create_index("ix_feature_session", ["session_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("not_before", sa.DateTime(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_by", sa.String(length=64), nullable=True),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_status_not_before", ["status", "not_before"], unique=False)
        batch_op.create_index(
            "uq_jobs_active_dedupe",
            ["dedupe_key"],
            unique=True,
            sqlite_where=sa.text("status IN ('PENDING', 'RUNNING')"),
        )

    op.create_table(
        "managed_playlists",
        sa.Column("managed_playlist_id", sa.String(length=36), nullable=False),
        sa.Column("playlist_id", sa.String(length=128), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("instance_id", sa.String(length=36), nullable=False),
        sa.Column("ownership_marker", sa.Text(), nullable=False),
        sa.Column("temperature", sa.Integer(), nullable=False),
        sa.Column("configured_target_size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("accepted_desired_hash", sa.String(length=64), nullable=True),
        sa.Column("setup_started_at", sa.DateTime(), nullable=True),
        sa.Column("setup_finished_at", sa.DateTime(), nullable=True),
        sa.Column("setup_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_published_at", sa.DateTime(), nullable=True),
        sa.Column("next_publish_after", sa.DateTime(), nullable=True),
        sa.Column("auto_publish_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("managed_playlist_id"),
        sa.UniqueConstraint("kind", name="uq_managed_playlist_kind"),
        sa.UniqueConstraint("playlist_id"),
    )
    op.create_table(
        "model_snapshots",
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("algorithm", sa.String(length=32), nullable=False),
        sa.Column("feature_schema_version", sa.String(length=24), nullable=False),
        sa.Column("parameters_blob", sa.LargeBinary(), nullable=False),
        sa.Column("trained_through_session_id", sa.String(length=36), nullable=True),
        sa.Column("trained_through_time", sa.DateTime(), nullable=True),
        sa.Column("training_counts_json", sa.JSON(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("model_id"),
    )
    with op.batch_alter_table("model_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_model_status", ["status"], unique=False)

    op.create_table(
        "playback_sessions",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("queue_id", sa.String(length=36), nullable=True),
        sa.Column("generation_id", sa.String(length=36), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("termination_reason", sa.String(length=32), nullable=True),
        sa.Column("effective_duration_seconds", sa.Float(), nullable=True),
        sa.Column("duration_source", sa.String(length=16), nullable=False),
        sa.Column("played_seconds", sa.Float(), nullable=False),
        sa.Column("played_ratio", sa.Float(), nullable=True),
        sa.Column("max_position_seconds", sa.Float(), nullable=False),
        sa.Column("seek_forward_seconds", sa.Float(), nullable=False),
        sa.Column("seek_backward_seconds", sa.Float(), nullable=False),
        sa.Column("seek_forward_count", sa.Integer(), nullable=False),
        sa.Column("seek_backward_count", sa.Integer(), nullable=False),
        sa.Column("buffered_seconds", sa.Float(), nullable=False),
        sa.Column("wall_clock_seconds", sa.Float(), nullable=False),
        sa.Column("explicit_rating", sa.String(length=16), nullable=True),
        sa.Column("early_skip", sa.Boolean(), nullable=False),
        sa.Column("mid_skip", sa.Boolean(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("ended_unqualified", sa.Boolean(), nullable=False),
        sa.Column("large_forward_seek", sa.Boolean(), nullable=False),
        sa.Column("replayed", sa.Boolean(), nullable=False),
        sa.Column("classification_basis", sa.String(length=16), nullable=False),
        sa.Column("qualified", sa.Boolean(), nullable=False),
        sa.Column("reward", sa.Float(), nullable=True),
        sa.Column("reward_version", sa.String(length=24), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("aggregation_version", sa.String(length=24), nullable=True),
        sa.Column("aggregated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("playback_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_started", ["started_at"], unique=False)

    op.create_table(
        "queue_generations",
        sa.Column("generation_id", sa.String(length=36), nullable=False),
        sa.Column("queue_id", sa.String(length=36), nullable=False),
        sa.Column("temperature", sa.Integer(), nullable=False),
        sa.Column("mood", sa.String(length=16), nullable=False),
        sa.Column("serving_policy", sa.String(length=32), nullable=False),
        sa.Column("serving_model_id", sa.String(length=36), nullable=True),
        sa.Column("shadow_model_id", sa.String(length=36), nullable=True),
        sa.Column("quality_score_source", sa.String(length=24), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("pool_watermark", sa.DateTime(), nullable=True),
        sa.Column("target_familiar_percent", sa.Integer(), nullable=False),
        sa.Column("actual_familiar_percent", sa.Integer(), nullable=False),
        sa.Column("relaxations_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("generation_id"),
    )
    with op.batch_alter_table("queue_generations", schema=None) as batch_op:
        batch_op.create_index("ix_generation_queue", ["queue_id"], unique=False)

    op.create_table(
        "remote_history_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("play_order", sa.Integer(), nullable=False),
        sa.Column("period_label", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "observed_at", "play_order", name="uq_remote_history_item"),
    )
    op.create_table(
        "remote_playlists",
        sa.Column("playlist_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("track_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("remote_deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("playlist_id"),
    )
    op.create_table(
        "schema_metadata",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "sync_runs",
        sa.Column("sync_run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("liked_count", sa.Integer(), nullable=False),
        sa.Column("playlist_count", sa.Integer(), nullable=False),
        sa.Column("history_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("sync_run_id"),
    )
    op.create_table(
        "telemetry_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_event_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("occurred_at_client", sa.DateTime(), nullable=False),
        sa.Column("received_at_server", sa.DateTime(), nullable=False),
        sa.Column("monotonic_ms", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_event_id"),
        sa.UniqueConstraint("session_id", "sequence_no", name="uq_event_session_sequence"),
    )
    with op.batch_alter_table("telemetry_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_events_session_sequence", ["session_id", "sequence_no"], unique=False
        )
        batch_op.create_index(
            "ix_events_type_received", ["event_type", "received_at_server"], unique=False
        )
        batch_op.create_index(
            "ix_events_video_received", ["video_id", "received_at_server"], unique=False
        )

    op.create_table(
        "track_affinity",
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("plays_1d", sa.Integer(), nullable=False),
        sa.Column("plays_7d", sa.Integer(), nullable=False),
        sa.Column("plays_30d", sa.Integer(), nullable=False),
        sa.Column("plays_all", sa.Integer(), nullable=False),
        sa.Column("completions", sa.Integer(), nullable=False),
        sa.Column("skips", sa.Integer(), nullable=False),
        sa.Column("replays", sa.Integer(), nullable=False),
        sa.Column("decayed_reward", sa.Float(), nullable=False),
        sa.Column("last_played_at", sa.DateTime(), nullable=True),
        sa.Column("last_liked_at", sa.DateTime(), nullable=True),
        sa.Column("last_skipped_at", sa.DateTime(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("aggregate_version", sa.String(length=24), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("video_id"),
    )
    op.create_table(
        "tracks",
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("metadata_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("album_id", sa.String(length=128), nullable=True),
        sa.Column("album_title", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("is_playable", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("remote_deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("video_id"),
    )
    op.create_table(
        "library_track_state",
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("is_liked", sa.Boolean(), nullable=False),
        sa.Column("is_disliked", sa.Boolean(), nullable=False),
        sa.Column("is_in_library", sa.Boolean(), nullable=False),
        sa.Column("remote_rating_synced_at", sa.DateTime(), nullable=True),
        sa.Column("desired_rating", sa.String(length=16), nullable=True),
        sa.Column("rating_revision", sa.Integer(), nullable=False),
        sa.Column("rating_synced_revision", sa.Integer(), nullable=False),
        sa.Column("rating_sync_status", sa.String(length=24), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["tracks.video_id"],
        ),
        sa.PrimaryKeyConstraint("video_id"),
    )
    op.create_table(
        "playlist_backups",
        sa.Column("backup_id", sa.String(length=36), nullable=False),
        sa.Column("managed_playlist_id", sa.String(length=36), nullable=False),
        sa.Column("publication_id", sa.String(length=36), nullable=True),
        sa.Column("items_json", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["managed_playlist_id"],
            ["managed_playlists.managed_playlist_id"],
        ),
        sa.PrimaryKeyConstraint("backup_id"),
    )
    with op.batch_alter_table("playlist_backups", schema=None) as batch_op:
        batch_op.create_index(
            "ix_backup_playlist_created", ["managed_playlist_id", "created_at"], unique=False
        )

    op.create_table(
        "playlist_publications",
        sa.Column("publication_id", sa.String(length=36), nullable=False),
        sa.Column("managed_playlist_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("target_generation_id", sa.String(length=36), nullable=True),
        sa.Column("quality_gate_version", sa.String(length=24), nullable=False),
        sa.Column("quality_gate_results_json", sa.JSON(), nullable=False),
        sa.Column("configured_target_size", sa.Integer(), nullable=False),
        sa.Column("effective_target_size", sa.Integer(), nullable=False),
        sa.Column("remote_before_json", sa.JSON(), nullable=False),
        sa.Column("desired_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("desired_hash", sa.String(length=64), nullable=False),
        sa.Column("expected_intermediate_hash", sa.String(length=64), nullable=True),
        sa.Column("applied_operations_json", sa.JSON(), nullable=False),
        sa.Column("remaining_item_changes", sa.Integer(), nullable=False),
        sa.Column("remaining_estimated_requests", sa.Integer(), nullable=False),
        sa.Column("verification_hash", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("not_before", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["managed_playlist_id"],
            ["managed_playlists.managed_playlist_id"],
        ),
        sa.PrimaryKeyConstraint("publication_id"),
    )
    with op.batch_alter_table("playlist_publications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_publication_playlist_status", ["managed_playlist_id", "status"], unique=False
        )

    op.create_table(
        "queue_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("generation_id", sa.String(length=36), nullable=False),
        sa.Column("queue_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("quality_expected", sa.Float(), nullable=False),
        sa.Column("familiarity", sa.String(length=16), nullable=False),
        sa.Column("reason_codes_json", sa.JSON(), nullable=False),
        sa.Column("played_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["queue_generations.generation_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generation_id", "position", name="uq_queue_item_position"),
    )
    with op.batch_alter_table("queue_items", schema=None) as batch_op:
        batch_op.create_index("ix_queue_items_queue", ["queue_id", "position"], unique=False)

    op.create_table(
        "remote_playlist_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("playlist_id", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("set_video_id", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["remote_playlists.playlist_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playlist_id", "position", name="uq_remote_item_position"),
    )
    op.create_table(
        "track_artists",
        sa.Column("track_id", sa.String(length=64), nullable=False),
        sa.Column("artist_id", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.artist_id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.video_id"],
        ),
        sa.PrimaryKeyConstraint("track_id", "artist_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track_artists")
    op.drop_table("remote_playlist_items")
    with op.batch_alter_table("queue_items", schema=None) as batch_op:
        batch_op.drop_index("ix_queue_items_queue")

    op.drop_table("queue_items")
    with op.batch_alter_table("playlist_publications", schema=None) as batch_op:
        batch_op.drop_index("ix_publication_playlist_status")

    op.drop_table("playlist_publications")
    with op.batch_alter_table("playlist_backups", schema=None) as batch_op:
        batch_op.drop_index("ix_backup_playlist_created")

    op.drop_table("playlist_backups")
    op.drop_table("library_track_state")
    op.drop_table("tracks")
    op.drop_table("track_affinity")
    with op.batch_alter_table("telemetry_events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_video_received")
        batch_op.drop_index("ix_events_type_received")
        batch_op.drop_index("ix_events_session_sequence")

    op.drop_table("telemetry_events")
    op.drop_table("sync_runs")
    op.drop_table("settings")
    op.drop_table("schema_metadata")
    op.drop_table("remote_playlists")
    op.drop_table("remote_history_items")
    with op.batch_alter_table("queue_generations", schema=None) as batch_op:
        batch_op.drop_index("ix_generation_queue")

    op.drop_table("queue_generations")
    with op.batch_alter_table("playback_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_started")

    op.drop_table("playback_sessions")
    with op.batch_alter_table("model_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_model_status")

    op.drop_table("model_snapshots")
    op.drop_table("managed_playlists")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_jobs_active_dedupe", sqlite_where=sa.text("status IN ('PENDING', 'RUNNING')")
        )
        batch_op.drop_index("ix_jobs_status_not_before")

    op.drop_table("jobs")
    with op.batch_alter_table("feature_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_feature_session")
        batch_op.drop_index("ix_feature_created")

    op.drop_table("feature_snapshots")
    with op.batch_alter_table("candidate_edges", schema=None) as batch_op:
        batch_op.drop_index("ix_candidate_expires")

    op.drop_table("candidate_edges")
    op.drop_table("artists")
    op.drop_table("artist_affinity")
    with op.batch_alter_table("api_call_ledger", schema=None) as batch_op:
        batch_op.drop_index("ix_ledger_started")
        batch_op.drop_index("ix_ledger_operation_started")

    op.drop_table("api_call_ledger")
    # ### end Alembic commands ###
